import { useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { identity } from "../../public/utils/about";

export default function AboutMe() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div>
      <div className="md:flex md:space-x-2 md:my-10 md:items-center md:justify-center text-center"></div>
      <div>
        <div className="xl:flex xl:items-center md:w-4/6 md:mx-auto mx-10 md:my-10 xl:gap-10 my-5 p-5 rounded-2xl space-y-5 md:space-y-0 border-white border-2 box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px">
          <Image
            src={identity.Selfie}
            alt="My profile"
            width={400}
            height={400}
            className="mx-auto rounded-2xl 2xl:w-[400px] w-[250px]"
          />
          <div>
            <div className="px-5 md:space-y-10 space-y-2 py-10 xl:py-12 md:mx-10 xl:mx-0">
              <div>
                <div className="space-y-3">
                  <h1 className="text-3xl md:py-5 text-blue-500 font-bold">
                    About me
                  </h1>
                  <h1 className="font-bold text-xl">
                    A Designer shaped by Curiosity and Elegance
                  </h1>
                  <p>
                    I design with a focus on clarity, elegance, and thoughtful
                    solutions and translate the design language into computer
                    language. My approach is grounded in curiosity, and I follow
                    visuals and data. I thrive on creating designs that feel
                    intuitive, foster connection, and adapt seamlessly to
                    real-world needs.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="md:w-4/6 md:mx-auto mx-10 my-20">
        <h2 className="font-bold py-3 text-2xl">My Design Principles</h2>
        <div className="md:grid md:grid-cols-3 md:gap-5 space-y-5 md:space-y-0">
          <div className="border-white border-2 rounded-xl p-2 space-y-3">
            <p className="font-semibold text-center underline">
              North Star Method
            </p>
            <p>
              I use North Star method to clearly identify the challenge, the
              users, the business, the limitations, and what is possible to
              bring together.
            </p>
          </div>
          <div className="border-white border-2 rounded-xl p-2 space-y-3">
            <p className="font-semibold text-center underline">Collaboration</p>
            <p>
              Collaboration is the key to success. I believe that, in a group
              project, UX Researchers help us to get great insights and
              developers help us to build a good product.
            </p>
          </div>
          <div className="border-white border-2 rounded-xl p-2 space-y-3">
            <p className="font-semibold text-center underline">Communication</p>
            <p>
              I always do my best to keep everything open and transparent to
              make sure that my partners and I are on the same page.
            </p>
          </div>
        </div>
      </div>

      <div className="md:w-4/6 md:mx-auto mx-10 my-20">
        <div className="md:flex md:items-center md:gap-5">
          <div className="md:w-full">
            <h2 className="font-bold py-3 md:text-2xl text-xl">
              How did my JOURNEY begin?
            </h2>
            <div className="xl:flex lg:items-end xl:items-center lg:gap-5">
              <div className="xl:w-5/6">
                <h3 className="py-3">As an undergrad...</h3>
                <p>
                  I was a lab assistant for a neuroscience research team in
                  Department of Psychology at University of New Brunswick (which
                  the campus is located in Fredericton, New Brunswick, Canada).
                  Although everything that we were interested in was looking at
                  the data that was measured and generated by computer (but in
                  which the input was made by users), we were basically
                  providing some physical and visual tools to the participants
                  to interact with during the experiments. The entire point of
                  this activity was to see how visuals (or tools) influence the
                  way we make decisions.
                </p>
              </div>
              <div className="w-full md:p-5 p-2 md:m-3 my-2 bg-gradient-to-br border-white border-2 box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px; bg-[#f6f6f6] text-center rounded-2xl">
                <span className="text-xs md:text-base">
                  sample photo - not real from the lab
                </span>
                <Image
                  src={identity.Neuroscience}
                  alt="Neuroscience"
                  width={800}
                  height={600}
                  className="rounded-2xl float-image pt-3"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Add remaining sections following this pattern, converting images to Next.js Image components and ensuring all links use <Link> */}

      <div className="md:w-4/6 md:mx-auto mx-10 my-20 bg-white p-5 rounded-2xl">
        <div className="md:flex md:items-center md:gap-5">
          <div>
            <h3 className="font-bold py-3 md:text-2xl text-base">
              Would you like to work with me?
            </h3>
            <p className="md:text-base text-sm">
              Do you have a design challenge? Let&#39;s talk identity it! I will
              be there with you in every step of the way from ideation to launch
              of the product.
            </p>
            <div className="py-3">
              <div className="flex items-center space-x-1">
                <p>Let&#39;s</p>
                <a
                  href="https://www.linkedin.com/in/johnjang94/"
                  className="text-blue-500"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  stay connected
                </a>
                <p>!</p>
              </div>
              <div className="md:flex md:items-center space-x-1">
                <p>You can also reach out to me</p>
                <div className="flex items-end">
                  <Link href="/contact">
                    <p className="text-blue-500">here</p>
                  </Link>
                  <p>.</p>
                </div>
              </div>
            </div>
          </div>
          <Image
            src={identity.Challenge}
            alt="My profile"
            width={500}
            height={500}
            className="mx-auto rounded-2xl 2xl:w-[500px] w-[450px]"
          />
        </div>
      </div>
    </div>
  );
}
